### ISSUE TITLE
nimi tan toki ante li ike tawa ilo jan sina!

### ISSUE THREAD

**Issue by increpare** [damaru2/tokipona_bot#1]
mi toki e "jan [_supa_ala_telo_en] la o lape pona a" la ilo li pali e sitelen nasa:

<img width="402" alt="Bildschirmfoto 2020-03-26 um 16 57 26" src="https://user-images.githubusercontent.com/465632/77667887-0d22ba00-6f83-11ea-987f-26adde72d841.png">

mi pilin e ni - sitelen "_" li pakala e ilo sina.

**Comment by damaru2** [comment]
I automatically break the line after 10 characters so it is readable on telegram. I just changed it so it treats "_word" as just one word. In any case, there will be places where the format will be slightly broken because http://lp.plop.me/ does weird things sometimes with the margins.
