### ISSUE TITLE
sitelen li sin ala lon ante pi sitelen “!”

### ISSUE THREAD

**Issue by increpare** [damaru2/tokipona_bot#2]
jan pona pi jan pona mi o, toki a!

mi sitelen e ni la mi lukin e sitelen pona: “pona a!”

ni la, mi weka e sitelen “!”, la sitelen li ante ala.  mi ante e nimi, la sitelen li ante.  taso mi ante e “!” anu “.” anu “,” taso, la sitelen li awen sama.

(mi pilin e ni - sina pali e sitelen “.png” pi kalama lasinu taso. sina weka ala weka e sitelen sama “!” tan nimi “.png”? )

**Comment by damaru2** [comment]
toki a! ni li ike mute, mi sona. taso ni li pakala pi ilo Telekam. sina sitelen e sitelen pi kulupu nasa wan ([a-zA-Z0-9/ en sitelen ante] ala. mi sona ala e kulupu lon) la ilo mi li kama ala jo e sona sin tan ilo Telekam. 

ni li ike. sina wile ante e sitelen la sina ken sitelen e sitelen sin lon pini. sama ni:
`@tokipona_bot pona a /r`
ilo mi li weka e pini. ilo mi li kama jo e sona sin. sina kama jo e sitelen sin.

**Comment by increpare** [comment]
jan Tamalu o, pona tawa sina, tawa sona sina!
