### ISSUE TITLE
o pana e nimi ni tawa ma "tag" pi lipu sina: #tokipona

### ISSUE THREAD

**Issue by increpare** [damaru2/tokipona_bot#3]
mi wile ken alasa e ilo sina lon lipu ni: https://github.com/topics/tokipona :)

sama sitelen ni:

<img width="451" alt="Bildschirmfoto 2020-04-17 um 01 36 18" src="https://user-images.githubusercontent.com/465632/79516494-e0c30080-804b-11ea-9558-e8177cc8b63e.png">

**Comment by damaru2** [comment]
a! pona tawa sina. ni li pona. mi pali e ni.
